# Stavily Enhanced Agent Configuration
# Implements AGENT_USE.md specification

agent:
  id: "enhanced-agent-001"
  name: "Enhanced Stavily Agent"
  type: "action"
  tenant_id: "stavily-tenant"
  environment: "dev"
  version: "1.0.0"
  region: "us-east-1"
  tags:
    - "enhanced"
    - "agent-use-spec"
  heartbeat: "30s"
  poll_interval: "10s"
  max_concurrent_tasks: 3
  task_timeout: "300s"
  
  # Base folder where everything is stored (logs, plugins, etc.)
  base_folder: "./agent-data"

api:
  # Server address constant - configurable orchestrator endpoint
  base_url: "https://orchestrator.stavily.com"
  agents_endpoint: "/agents/v1"
  timeout: "30s"
  retry_attempts: 3
  retry_delay: "5s"
  rate_limit_rps: 10
  max_idle_conns: 10
  idle_conn_timeout: "90s"
  user_agent: "Stavily-Enhanced-Agent/1.0.0"

security:
  tls:
    enabled: false
    min_version: "1.3"
  auth:
    method: "jwt"
    token_file: "agent.jwt"  # Will be expanded to {base_folder}/config/certificates/agent.jwt
    token_ttl: "1h"
  sandbox:
    enabled: true
    max_memory: 134217728  # 128MB
    max_cpu: 0.5
    max_exec_time: "30s"
    max_file_size: 10485760  # 10MB
    network_access: true  # Allow network access for API communication
  audit:
    enabled: true
    log_file: "enhanced-agent-audit.log"  # Will be expanded to {base_folder}/logs/audit/
    max_size: 100
    max_backups: 10
    max_age: 30
    compress: true

plugins:
  directory: "plugins"  # Will be expanded to {base_folder}/plugins
  auto_load: true
  watch_changes: true
  update_check: "1h"
  timeout: "30s"
  max_concurrent: 3
  registry:
    url: "https://plugins.stavily.dev"
    auth: false
    cache_dir: "cache/plugins"  # Will be expanded to {base_folder}/cache/plugins
    cache_ttl: "24h"

logging:
  level: "info"
  format: "json"
  output: "file"
  file: "enhanced-agent.log"  # Will be expanded to {base_folder}/logs/enhanced-agent.log
  max_size: 100
  max_backups: 5
  max_age: 30
  compress: true

health:
  enabled: true
  port: 8081
  path: "/health"
  interval: "30s"
  timeout: "10s"

metrics:
  enabled: true
  port: 9091
  path: "/metrics"
  namespace: "stavily_enhanced" 