# Stavily Sensor Agent - Development Configuration

agent:
  id: "sensor-dev-001"
  name: "Development Sensor Agent"
  type: "sensor"
  organization_id: "dev-tenant"
  base_dir: "/opt/stavily/agent-{AGENT_ID}"
  environment: "development"
  tags:
    - "development"
    - "monitoring"
  heartbeat_interval: "30s"
  registration_retry_interval: "60s"

api:
  base_url: "https://agents.stavily.dev"
  timeout: "30s"
  retry:
    max_attempts: 3
    backoff: "exponential"
    initial_interval: "1s"
    max_interval: "60s"
  auth:
    type: "jwt"
    token_file: "/opt/stavily/agent-{AGENT_ID}/config/certificates/agent.jwt"
    refresh_threshold: "5m"
  rate_limit:
    requests_per_second: 10
    burst: 20

security:
  sandbox:
    enabled: true
    user: "stavily"
    chroot: "/opt/stavily"
  tls:
    enabled: false  # Disabled for development
    min_version: "1.3"
    cipher_suites: []
  audit:
    enabled: true
    file: "/opt/stavily/agent-{AGENT_ID}/logs/audit/sensor-audit.log"

logging:
  level: "debug"
  format: "text"  # Use text format for development
  file: "/opt/stavily/agent-{AGENT_ID}/logs/sensor-agent.log"
  max_size: 100
  max_backups: 10
  max_age: 30
  compress: true

health:
  enabled: true
  port: 8080
  path: "/health"
  bind: "0.0.0.0"

metrics:
  enabled: true
  port: 9090
  path: "/metrics"
  bind: "127.0.0.1"
  namespace: "stavily_sensor"

# Sensor-specific settings
sensor:
  trigger_check_interval: "10s"
  max_concurrent_triggers: 5
  trigger_timeout: "30s"
  event_buffer_size: 1000
  batch_size: 10
  flush_interval: "5s" 