# Stavily Sensor Agent - Development Configuration

agent:
  id: "sensor-dev-001"
  name: "Development Sensor Agent"
  type: "sensor"
  tenant_id: "dev-tenant"
  environment: "dev"
  version: "1.0.0"
  region: "us-east-1"
  tags:
    - "development"
    - "monitoring"
  heartbeat: "30s"
  # Action agent specific fields (required by validation even for sensor agents)
  poll_interval: "30s"
  max_concurrent_tasks: 5
  task_timeout: "60s"

api:
  base_url: "https://agents.stavily.dev"
  agents_endpoint: "/api/v1/agents"
  timeout: "30s"
  retry_attempts: 3
  retry_delay: "5s"
  rate_limit_rps: 10
  max_idle_conns: 10
  idle_conn_timeout: "90s"
  user_agent: "Stavily-Sensor-Agent/1.0.0"

security:
  tls:
    enabled: false
    min_version: "1.3"
  auth:
    method: "jwt"
    token_file: "/opt/stavily/agent-{AGENT_ID}/config/certificates/agent.jwt"
    token_ttl: "1h"
  sandbox:
    enabled: true
    max_memory: 134217728  # 128MB in bytes
    max_cpu: 0.5  # 0.5 CPU cores
    max_exec_time: "30s"
    max_file_size: 10485760  # 10MB in bytes
    network_access: false
  audit:
    enabled: true
    log_file: "/opt/stavily/agent-{AGENT_ID}/logs/audit/sensor-audit.log"
    max_size: 100
    max_backups: 10
    max_age: 30

logging:
  level: "debug"
  format: "text"
  output: "file"
  file: "/opt/stavily/agent-{AGENT_ID}/logs/sensor-agent.log"
  max_size: 100
  max_backups: 10
  max_age: 30
  compress: true

health:
  enabled: true
  port: 8080
  path: "/health"
  interval: "30s"
  timeout: "10s"

metrics:
  enabled: true
  port: 9090
  path: "/metrics"
  namespace: "stavily_sensor"

plugins:
  directory: "/opt/stavily/agent-{AGENT_ID}/plugins"
  auto_load: true
  watch_changes: true
  update_check: "1h"
  timeout: "30s"
  max_concurrent: 5
  registry:
    url: "https://plugins.stavily.dev"
    auth: false
    cache_dir: "/opt/stavily/agent-{AGENT_ID}/cache/plugins"
    cache_ttl: "24h"

# Sensor-specific settings
sensor:
  trigger_check_interval: "10s"
  max_concurrent_triggers: 5
  trigger_timeout: "30s"
  event_buffer_size: 1000
  batch_size: 10
  flush_interval: "5s" 